language: python

python: "3.6"

services:
  - postgresql

env:
  global:
    - CC_TEST_REPORTER_ID=$reporter_id

install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls

before_script:
  - export DB_NAME='fusion_db'
  - export DB_USER='postgres'
  - psql -c 'create database fusion_db;' -U postgres
  - python manage.py makemigrations
  - python manage.py migrate
  - export CC_TEST_REPORTER_ID=$reporter_id
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script: coverage run --source='.' manage.py test && coverage report

after_success:
- ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  - coveralls
