language: python

python: "3.7"

addons:
  postgresql: "9.4"

install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls

before_script:
  - psql -c 'create database fusion;' -U postgres
  - python manage.py makemigrations
  - python manage.py migrate

script: coverage run --source='fusion/apps' manage.py test && coverage report

after_success: coveralls
